version: "3.9"
services:
  web:
    build: ./api/
    ports:
      - "4000:8080"
  mongo:
    build: 
      context: ./api/
      dockerfile: Dockerfile.mongo
    ports:
      - "4001:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: urlshortener