name: Lint
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v1
        with:
          repository: JJ-Kidd/primary-bid-tech-test

      - name: Install dependencies
        run: yarn install

      - name: Run linting
        run: yarn lint